import math
from typing import Dict
from src.inference.schemas import InferenceInput, InferenceOutput
from src.inference.feature_contract import build_feature_vector
from src.inference.model_loader import CloudSenseModelManager

class CloudSensePredictor:
    """
    The main execution boundary for local inference.
    """
    def __init__(self, model_manager: CloudSenseModelManager):
        self.model_manager = model_manager
        
    def predict(self, input_data: InferenceInput) -> InferenceOutput:
        """
        Takes a strict feature input, constructs the canonical vector, runs
        predictions across H1-H7, and returns a strict output dictionary.
        Negative values are clamped to 0.0 at the output boundary.
        """
        # 1. Feature construction (converts to exact order 2D numpy array)
        features = build_feature_vector(input_data)
        
        predictions: Dict[str, float] = {}
        
        # 2. Iteratively predict using the 7 independent horizons
        for h in range(1, 8):
            horizon_key = f"h{h}"
            booster = self.model_manager.get_model(horizon_key)
            
            # Predict returns an array, extract the single scalar value
            pred_arr = booster.predict(features)
            pred_val = float(pred_arr[0])
            
            # Reject NaNs or Infinity generated by the model
            if math.isnan(pred_val) or math.isinf(pred_val):
                raise ValueError(f"Model {horizon_key} returned non-finite prediction: {pred_val}")
            
            # 3. Clamp negative values to exactly 0.0
            if pred_val < 0.0:
                pred_val = 0.0
                
            predictions[horizon_key] = pred_val
            
        # 4. Strict output validation
        return InferenceOutput(**predictions)
